In [1]:
import time
import pandas as pd
import numpy as np
import requests
import json
import ipywidgets as widgets
from numpy.linalg import inv

In [2]:
### Start at A ###
def start_at_A(X_a, C_seed, C_min, C_max): # df: import data in DataFrame Format

    # Generate random numbers and add to data at Data Site A
#     np.random.seed(0)
    A_randoms = np.random.randint(C_min, C_max, len(X_a))
        
    # C_noises is shared between A and B 
    np.random.seed(C_seed)
    C_matrix = np.random.randint(C_min, C_max, (len(X_a), len(X_a)))

    Sum_noises_A = np.add(X_a, np.dot(C_matrix.transpose(), A_randoms)) # which will be sent to B

    return np.array(A_randoms), np.array(Sum_noises_A), 

def communication_at_A(X_a, A_randoms, Sum_noises_AB, Sum_noises_B, B_divide_set):
    
    ### At site A ###
    A_randoms_Sumset = []

    for j in range(0, int(len(X_a)/B_divide_set)):
        temp = 0
        for k in range(0, B_divide_set):
            temp = temp + A_randoms[B_divide_set*j + k]
        A_randoms_Sumset.append(temp)
    
    Sum_noises_B_Arand = np.subtract(Sum_noises_AB, np.dot(A_randoms,Sum_noises_B))

    # Calculate X_a.T * X_a locally at data site A 
    XaTXa = np.matrix(X_a).T * np.matrix(X_a)

    
    return np.array(A_randoms_Sumset), np.array(Sum_noises_B_Arand), np.array(XaTXa)

In [3]:
style = {'description_width': 'initial'}
uniLayout = widgets.Layout(width='50%', height='50px')

Q0 = widgets.RadioButtons(
    options=['No', 'Yes'],
    description='Are you a meat lover?',
    style=style, 
    layout=uniLayout
)

Q1 = widgets.RadioButtons(
    options=['Hell No', 'YES!'],
    description='Do you like pizza with pineapple on top?',
    style=style, 
    layout=uniLayout
)

Q2 = widgets.RadioButtons(
    options=['No', 'Yes'],
    description='Do you add sugar in coffee?',
    style=style, 
    layout=uniLayout
)

Q3 = widgets.RadioButtons(
    options=['No, only salt', 'Tons of sauce'],
    description='Do you eat fries with sauce?',
    style=style, 
    layout=uniLayout
)

Q4 = widgets.RadioButtons(
    options=['OMG, NO', 'LOVE'],
    description='Do you like eating haring?',
    style=style, 
    layout=uniLayout
)

Q5 = widgets.RadioButtons(
    options=['Nope', 'Sure, what else?'],
    description='Do you frequently eat potatoes?',
    style=style, 
    layout=uniLayout
)

In [4]:
display(Q0, Q1, Q2, Q3, Q4, Q5)

RadioButtons(description='Are you a meat lover?', layout=Layout(height='50px', width='50%'), options=('No', 'Y…

RadioButtons(description='Do you like pizza with pineapple on top?', layout=Layout(height='50px', width='50%')…

RadioButtons(description='Do you add sugar in coffee?', layout=Layout(height='50px', width='50%'), options=('N…

RadioButtons(description='Do you eat fries with sauce?', layout=Layout(height='50px', width='50%'), options=('…

RadioButtons(description='Do you like eating haring?', layout=Layout(height='50px', width='50%'), options=('OM…

RadioButtons(description='Do you frequently eat potatoes?', layout=Layout(height='50px', width='50%'), options…

In [16]:
C_seed = 1
C_min = 0
C_max = 5
B_divide_set = 3
X_a = np.array([Q0.index,Q1.index,Q2.index,Q3.index,Q4.index,Q5.index])
A_randoms, Sum_noises_A = start_at_A(X_a, C_seed, C_min, C_max)
# print(X_a)
# print(A_randoms)
print(Sum_noises_A)

[30 26 31 35 30 27]


In [17]:
################################################################
### At site B ###
################################################################
def start_at_B(X_b, C_seed, C_min, C_max, Sum_noises_A, B_divide_set): # df: import data in DataFrame Format
    
    np.random.seed(C_seed) # seeds, range of C_noises is shared between A and B 
    C_matrix = np.random.randint(C_min ,C_max , (len(Sum_noises_A), len(Sum_noises_A)))

    Sum_coef_B = []
    for j in range(0, len(Sum_noises_A)):
        Sum_coef_B.append(np.dot(C_matrix[j].transpose(), X_b)) 


    np.random.seed(0)
    B_random_set = np.random.randint(0,5, int(len(X_b)/B_divide_set))

                                 
    B_random_inter = []
    for j in range(0, len(B_random_set)): 
        for k in range(0, B_divide_set):
            B_random_inter.append(B_random_set[j])

    Sum_noises_B = np.array(Sum_coef_B) + np.array(B_random_inter)

    # Add noises dataset A to the dataset B
    Sum_noises_AB = np.dot(Sum_noises_A, X_b)

    return np.array(B_random_set), np.array(Sum_noises_AB), np.array(Sum_noises_B)

In [27]:
style = {'description_width': 'initial'}
uniLayout = widgets.Layout(width='50%', height='50px')

Q0B = widgets.RadioButtons(
    options=['No', 'Yes'],
    description='Are you a meat lover?',
    style=style, 
    layout=uniLayout
)

Q1B = widgets.RadioButtons(
    options=['Hell No', 'YES!'],
    description='Do you like pizza with pineapple on top?',
    style=style, 
    layout=uniLayout
)

Q2B = widgets.RadioButtons(
    options=['No', 'Yes'],
    description='Do you add sugar in coffee?',
    style=style, 
    layout=uniLayout
)

Q3B = widgets.RadioButtons(
    options=['No, only salt', 'Tons of sauce'],
    description='Do you eat fries with sauce?',
    style=style, 
    layout=uniLayout
)

Q4B = widgets.RadioButtons(
    options=['OMG, NO', 'LOVE'],
    description='Do you like eating haring?',
    style=style, 
    layout=uniLayout
)

Q5B = widgets.RadioButtons(
    options=['Nope', 'Sure, what else?'],
    description='Do you frequently eat potatoes?',
    style=style, 
    layout=uniLayout
)

In [28]:
display(Q0B, Q1B, Q2B, Q3B, Q4B, Q5B)

RadioButtons(description='Are you a meat lover?', layout=Layout(height='50px', width='50%'), options=('No', 'Y…

RadioButtons(description='Do you like pizza with pineapple on top?', layout=Layout(height='50px', width='50%')…

RadioButtons(description='Do you add sugar in coffee?', layout=Layout(height='50px', width='50%'), options=('N…

RadioButtons(description='Do you eat fries with sauce?', layout=Layout(height='50px', width='50%'), options=('…

RadioButtons(description='Do you like eating haring?', layout=Layout(height='50px', width='50%'), options=('OM…

RadioButtons(description='Do you frequently eat potatoes?', layout=Layout(height='50px', width='50%'), options…

In [29]:
B_divide_set = 3
X_b = np.array([Q0B.index,Q1B.index,Q2B.index,Q3B.index,Q4B.index,Q5B.index])
B_random_set, Sum_noises_AB, Sum_noises_B = start_at_B(X_b, C_seed, C_min, C_max, Sum_noises_A, B_divide_set)
print(B_random_set)
print(Sum_noises_AB)
print(Sum_noises_B)

[4 0]
92
[ 8 11 13  2  5  6]


In [30]:
# Sum_noises_AB = 76
# Sum_noises_B = [7, 5, 10, 13, 6, 4]

In [31]:
A_randoms_Sumset, Sum_noises_B_Arand, XaTXa = communication_at_A(X_a, A_randoms, \
                                                                 Sum_noises_AB, Sum_noises_B, B_divide_set)
print(A_randoms_Sumset)
print(Sum_noises_B_Arand)

[9 6]
-33


In [32]:
################################################################
################################################################
def Final_at_B(X_b, A_randoms_Sumset, Sum_noises_B_Arand, XaTXa, B_random_set, B_divide_set):

    ### At site B ###
    rand_sums = 0

    for j in range(0, len(B_random_set)):
        rand_sums = rand_sums + A_randoms_Sumset[j] * B_random_set[j]
    
    outcomes = Sum_noises_B_Arand + rand_sums

    return outcomes

In [33]:
Final_at_B(X_b, A_randoms_Sumset, Sum_noises_B_Arand, XaTXa, B_random_set, B_divide_set)

3

In [34]:
np.dot(np.array(X_a), np.array(X_b))

3

In [25]:
X_b

array([0, 0, 0, 0, 0, 0])

In [26]:
X_a

array([0, 0, 0, 1, 1, 1])